### ISSUE TITLE
Remove `AnyPackage.PowerShellGet` from PowerShell Gallery?

### ISSUE THREAD

**Issue by o-l-a-v** [anypackage/psresourceget#38]
`AnyPackage.PowerShellGet` was renamed to `AnyPackage.PSResourceGet`?

But `AnyPackage.PowerShellGet` is still available in PowerShell Gallery:

* https://www.powershellgallery.com/packages/AnyPackage.PowerShellGet

**Comment by ThomasNieto** [comment]
Thanks for reminding me, I meant to do that but forgot. `AnyPackage.PowerShellGet` has been unlisted to remove any confusion.
